/* Solution to ACM UVa Problem 101 - The Blocks Problem  */
/* Author- Mrunmoy Samal Copyright© Material*/
/* Date: 9th December 2007 */
/* If you are satisfied with the solution do 
   send a mail to mrunmoy@yahoo.com */

#include <iostream>
#include <ctype.h>
#include <stdlib.h>
using std::cin;
using std::cout;

/* main entry point of the code */
int main(void)
{
	int numBlocks;
	char cmd1[5]; // move 9 onto 1
	char cmd2[5];
	int num1;
	int num2;
	/* how many number of blocks are to there? */
	//scanf("%d",&numBlocks);
    
    /*while(strcmp(cmd1,"quit") != 0)
    {
        cin >> cmd1 >> num1 >> cmd2 >> num2;
        cout << cmd1 << " " << num1 << " " << cmd2 << " " << num2 << "\n";
    }*/
    
    printf("%c",getch());
	return 0;
}
